version: '3'

volumes:
  pgdata:
  static_files:
services:
  nginx:
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    volumes:
      - static_files:/static_files
    ports:
      - 8080:8080
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    command: gunicorn -w 4 django_blog.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/app
      - static_files:/static_files
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: luisweb
      POSTGRES_DB: djangoblogdb
      POSTGRES_PASSWORD: dbtesting
    volumes:
      - pgdata:/var/lib/postgresql/data
